### ISSUE TITLE
 Unrecognized argument of account

### ISSUE THREAD

**Issue by KoiFDCV** [varyg1001/nyaaup#23]
I imported the certificate but an error message was pushed 
`nyaaup: error: unrecognized arguments: -add user:pass`

**Comment by varyg1001** [comment]
USAGE: nyaaup auth [-h] [-c USER:PASS] [-an NAME] [-ap NAME] [-p NAME]

╭─ Options ─────────────────────────────────────────────────────────────────╮
│   -h, --help                  show this help message and exit             │
│   -c, --credential USER:PASS  Add or replace credential.                  │
│   -an, --announces NAME       Add new announces url to config.            │
│   -ap, --api NAME             Add or replace api.                         │
│   -p, --provider NAME         Provider name for config. (default: nyaasi) │
╰───────────────────────────────────────────────────────────────────────────╯
