### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specifi

### ISSUE THREAD

**Issue by KoiFDCV** [varyg1001/nyaaup#25]
```
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
I can't determine my own fault when looking at it.

**Comment by varyg1001** [comment]
How is you command look like and the file is there? (I don't use it on win but I tested and worked)

**Comment by KoiFDCV** [comment]
`nyaaup up -A -H -C -p 3 -M --skip-myanimelist -c 3 "/path/to/file/"`

**Comment by varyg1001** [comment]
And does the file exists? (correct name?)

**Comment by KoiFDCV** [comment]
Do you mean the name of the file is correct? The name of the file doesn't seem to matter, but what is that `WinError 2`?

**Comment by varyg1001** [comment]
Because you didn't pate the full error I though it's missing the inptu file, but most likly it's probelm with your python install not with the nyaaup. But can't really say much without know what it's missing.
